name: Build

on:
  push:
    branches: ['*']
    tags: ['*']
    paths-ignore: 
      - "**/*.md"

env:
  PROJECT_NAME: DoombubblesTweaks

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        
      - name: Setup dotNET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Download Multitool
        uses: robinraju/release-downloader@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ShinyHobo/BG3-Modders-Multitool
          fileName: bg3-modders-multitool.zip
          tarBall: false
          zipBall: false
          latest: true
          extract: true
  
      - name: Build Pak
        run: dotnet ./bg3-modders-multitool.dll -s "./${{ env.PROJECT_NAME }}" -d "./${{ env.PROJECT_NAME }}.pak" -c 1

      - name: Upload Mod
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.PROJECT_NAME }}.pak

      - name: Build Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet ./bg3-modders-multitool.dll -s "./${{ env.PROJECT_NAME }}" -d "./${{ env.PROJECT_NAME }}.zip" -c 1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.PROJECT_NAME }}.zip
            UpdateDoombubblesTweaks.bat
          body_path: LATEST.md
          fail_on_unmatched_files: true