name: Build

on:
  push:
    branches: ['*']
    tags: ['*']

env:
  PROJECT_NAME: DoombubblesTweaks

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      # Optional
      - name: Timezone
        run: TZUTIL /s "Pacific Standard Time"

      - name: Clone Repo
        uses: actions/checkout@master

      - name: Download Multitool
        uses: robinraju/release-downloader@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ShinyHobo/BG3-Modders-Multitool
          fileName: bg3-modders-multitool.zip
          tarBall: false
          zipBall: false
          latest: true
          extract: true

      - name: Download Unitool
        uses: robinraju/release-downloader@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: doombubbles/BG3-Modders-Unitool
          fileName: bg3-modders-unitool.zip
          tarBall: false
          zipBall: false
          latest: true
          extract: true
  
      - name: Build Pak
        run: ./bg3-modders-unitool.exe "./${{ env.PROJECT_NAME }}"

      - name: Upload Mod
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.PROJECT_NAME }}.pak

      - name: Build Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: ./bg3-modders-unitool.exe -z "./${{ env.PROJECT_NAME }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.PROJECT_NAME }}.pak
            ${{ env.PROJECT_NAME }}.zip
          body_path: LATEST.md
          fail_on_unmatched_files: true