name: Wiki

on:
  push:
    branches: ['main']
    paths:  
      - "Wiki/**/*"
      - "**/wiki.yml"

env:
  PROJECT_NAME: DoombubblesTweaks

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@master

      - name: Set Permissions
        run: chmod +x ./bin/ProcessTemplates

      - name: Prepare Wiki Folder
        run: |
          mv Wiki/README.md Wiki/Home.md

      - name: Process Mod Templates
        run: ./bin/ProcessTemplates

      - name: Process Wiki Templates
        run: ./bin/ProcessTemplates -s Wiki -d build/Wiki -v DoombubblesTweaks -v build/DoombubblesTweaks/Localization
          
      - name: Upload to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: build/Wiki/
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}