name: Wiki

on:
  push:
    branches: ["main"]
    paths:
      - "Wiki/**/*"
      - "**/wiki.yml"

jobs:
  wiki:
    runs-on: windows-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master

      - name: Process DoombubblesTweaks
        run: ./bin/ProcessTemplates.exe -s DoombubblesTweaks -d build/DoombubblesTweaks

      - name: Process WoWSubclasses
        run: ./bin/ProcessTemplates.exe -s WoWSubclasses -d build/WoWSubclasses

      - name: Process WoWDeathKnight
        run: ./bin/ProcessTemplates.exe -s WoWDeathKnight -d build/WoWDeathKnight

      - name: Process Wiki Templates
        run: ./bin/ProcessTemplates.exe -s Wiki -d build/Wiki -v DoombubblesTweaks -v build/DoombubblesTweaks/Localization -v WoWDeathKnight -v build/WoWDeathKnight/Localization -v WoWSubclasses -v build/WoWSubclasses/Localization

      - name: Upload to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: build/Wiki/
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
